# Generated by Django 5.0.6 on 2024-05-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ANO", models.IntegerField()),
                ("contrato_no", models.CharField(max_length=100)),
                ("tipo_de_contrato", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=255)),
                ("entidad", models.CharField(max_length=255)),
                ("rup", models.CharField(blank=True, max_length=100, null=True)),
                ("contrato", models.CharField(max_length=100)),
                ("smmlv", models.DecimalField(decimal_places=2, max_digits=10)),
                ("secop", models.CharField(blank=True, max_length=100, null=True)),
                ("contrato2", models.CharField(blank=True, max_length=100, null=True)),
                ("acta_final", models.CharField(blank=True, max_length=100, null=True)),
                ("objeto", models.TextField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_final", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "smmlv3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "adicion",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "part_porc",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Part. %"
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "smmlv4",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
                "ordering": ["-ANO"],
            },
        ),
    ]
