# Generated by Django 5.0.6 on 2024-05-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contratos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="fecha_final",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="fecha_inicio",
            field=models.DateTimeField(),
        ),
    ]
