# Generated by Django 5.0.6 on 2024-06-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contratos", "0003_contrato_created_alter_contrato_fecha_final_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
